import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:material_ui/material_ui.dart';

class AppThemes {
  static final Map<String, ThemeData> themes = {
    'Blue': FlexThemeData.light(
      scheme: FlexScheme.blue,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'AquaBlue': FlexThemeData.light(
      scheme: FlexScheme.aquaBlue,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'Green': FlexThemeData.light(
      scheme: FlexScheme.green,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'Gold': FlexThemeData.light(
      scheme: FlexScheme.gold,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'Teal': FlexThemeData.light(
      scheme: FlexScheme.tealM3,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'Purple': FlexThemeData.light(
      scheme: FlexScheme.purpleM3,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
    'Red': FlexThemeData.light(
      scheme: FlexScheme.red,
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        // drawerRadius: 0.0,
        drawerBackgroundSchemeColor: SchemeColor.primary,
        navigationRailUseIndicator: true,
        navigationRailBackgroundSchemeColor: SchemeColor.primary,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    ),
  };
}
