-- =====================================================================
-- AiCMHCS 智慧儿童心理保健系统 —— 02 建表（以应用账号 AICMHCS 执行）
-- =====================================================================
WHENEVER SQLERROR CONTINUE

DROP TABLE IF EXISTS SYS_LOGIN_LOG;
DROP TABLE IF EXISTS SYS_USER;

-- ---------------------------------------------------------------------
-- 系统用户表
-- ---------------------------------------------------------------------
CREATE TABLE SYS_USER (
  ID            BIGINT IDENTITY(1, 1) NOT NULL,
  USERNAME      VARCHAR(50)  NOT NULL,
  PASSWORD      VARCHAR(128) NOT NULL,
  REAL_NAME     VARCHAR(50)  NOT NULL,
  ROLE_CODE     VARCHAR(20)  NOT NULL,
  PHONE         VARCHAR(20),
  STATUS        INT DEFAULT 1 NOT NULL,
  LAST_LOGIN_AT TIMESTAMP(0),
  CREATED_AT    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SYS_USER PRIMARY KEY (ID),
  CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME)
);

COMMENT ON TABLE SYS_USER IS '系统用户表';
COMMENT ON COLUMN SYS_USER.ID IS '用户ID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '登录名';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '口令（salt:sha256hex）';
COMMENT ON COLUMN SYS_USER.REAL_NAME IS '姓名';
COMMENT ON COLUMN SYS_USER.ROLE_CODE IS '角色：ADMIN/DOCTOR/TEACHER/PARENT';
COMMENT ON COLUMN SYS_USER.PHONE IS '联系电话';
COMMENT ON COLUMN SYS_USER.STATUS IS '状态：1=启用 0=停用';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_AT IS '最近登录时间';
COMMENT ON COLUMN SYS_USER.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATED_AT IS '更新时间';

-- ---------------------------------------------------------------------
-- 登录日志表（审计）
-- ---------------------------------------------------------------------
CREATE TABLE SYS_LOGIN_LOG (
  ID           BIGINT IDENTITY(1, 1) NOT NULL,
  USER_ID      BIGINT,
  USERNAME     VARCHAR(50) NOT NULL,
  LOGIN_IP     VARCHAR(50),
  LOGIN_TIME   TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOGIN_RESULT VARCHAR(20) NOT NULL,
  FAIL_REASON  VARCHAR(100),
  CONSTRAINT PK_SYS_LOGIN_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_LOGIN_LOG IS '登录日志表';
COMMENT ON COLUMN SYS_LOGIN_LOG.USER_ID IS '用户ID（登录失败且用户不存在时为空）';
COMMENT ON COLUMN SYS_LOGIN_LOG.LOGIN_IP IS '登录来源IP';
COMMENT ON COLUMN SYS_LOGIN_LOG.LOGIN_TIME IS '登录时间';
COMMENT ON COLUMN SYS_LOGIN_LOG.LOGIN_RESULT IS '结果：SUCCESS/FAIL';
COMMENT ON COLUMN SYS_LOGIN_LOG.FAIL_REASON IS '失败原因';

CREATE INDEX IDX_SYS_LOGIN_LOG_TIME ON SYS_LOGIN_LOG (LOGIN_TIME);

COMMIT;
EXIT;
